version: '3.7'

services:
  elasticsearch:
    user: 0:0
    container_name: elasticsearch
    image: elasticsearch:7.16.1
    volumes:
      - ./elasticsearch_config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - data01:/usr/share/elasticsearch/data # том находится в каталоге по умолчанию /var/lib/docker/volumes/
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    container_name: logstash
    image: logstash:7.16.2
    volumes:
      - ./logstash_config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash_pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash_pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:7.16.1
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana_config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"

  beats:
    container_name: filebeat
    user: root
    image: elastic/filebeat:7.16.2
    volumes:
      - ./filebeat_config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./host_metrics_app/:/host_metrics_app/:ro
    command: ["--strict.perms=false"]
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  data01:
    driver: local

networks:
  elk:
    driver: bridge
